\LoadClass[11pt,a4paper,sans]{moderncv}
% options: a4, a5, b5, legalpaper, executivepaper, landscape

% Moderncv themes
\moderncvstyle{banking} %Style options 'casual' (default), 'classic',
                        %'oldstyle', 'banking'
\moderncvcolor{black} %color options 'blue' (default), 'orange', 'purple',
                      %'grey', 'black', 'green', 'red'

%personal data
\name{NaDario `Dario'}{Seays}

\title{Jr Software Developer}
\address{5523 Wellborn Creek Drive}
        {Lithonia, Ga, 30058}{USA}
\phone[mobile]{1+~(470)~265~9368}
\email{nadario.seays@gmail.com}
\social[github][github.com/knosence]{knosence}
\social[linkedin][linkedin.com/in/nadario-seays-a390962a]
