\LoadClass[11pt,a4paper,sans]{moderncv}
% options: a4, a5, b5, legalpaper, executivepaper, landscape

% Moderncv themes
\moderncvstyle{banking} %Style options 'casual' (default), 'classic',
                        %'oldstyle', 'banking'
\moderncvcolor{red} %color options 'blue' (default), 'orange', 'purple',
                      %'grey', 'black', 'green', 'red'

%personal data
\name{NaDario}{Seays}

\title{Jr Developer}
\address{5523 Wellborn Creek Drive}
        {Lithonia, Ga, 30058}{USA}
\phone[mobile]{1+~(470)~265~9368}
\email{nadario.seays@gmail.com}
\homepage{www.nadarioseays.com}
\social[github][github.com/knosence]{knosence}
\social[linkedin][linkedin.com/in/nadario-seays-a390962a]{NaDario Seays}

%character encoding
\RequirePackage[utf8]{inputenc}
\RequirePackage{geometry} %changes margins across ther page
\geometry{
  left = 15mm,
  right = 15mm,
  top = 15mm,
  bottom = 5mm
}

